# Generated by Django 2.0.2 on 2020-04-30 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='名称')),
                ('publish_time', models.DateField(verbose_name='发布时间')),
                ('text', models.TextField(verbose_name='正文内容')),
                ('url', models.URLField(unique=True, verbose_name='网页的url')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleTagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flux.ArticleModel')),
            ],
            options={
                'db_table': 'article_tags',
            },
        ),
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_tag', models.CharField(max_length=256, verbose_name='大标签')),
                ('small_tag', models.CharField(max_length=256, verbose_name='小标签')),
                ('ArticleModel', models.ManyToManyField(through='flux.ArticleTagModel', to='flux.ArticleModel')),
            ],
        ),
        migrations.AddField(
            model_name='articletagmodel',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flux.TagsModel'),
        ),
    ]
